name: GitHub Actions Example
on: [push]		
jobs:
  Explore-GitHub-Actions: #Job name
    runs-on: alpine #image to use to execute steps
    steps:
      - run: apt update
      - run: apt full-upgrade
      - run: echo " The job was automatically triggered by a ${{Github.event_name }} event." # When no name is defined the cmd is choosen as step alias
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ GitHub.ref }} and your repository is ${{ GitHub.repository }}."
      - name: Check out repository code #represents the name of the inner step within the job
        uses: actions/checkout@v3
      - run: echo " The ${{ GitHub.repository }} repository has been cloned to the runner." 
      - run: echo " The workflow is now ready to test your code on the runner."
        name: List files in the repository
      - run: |
          ls ${{ GitHub.workspace }}
      - run: echo " This job's status is ${{ job.status }}."